logging:
  level: 
    root: FATAL
  file:
    name: tasks.log
    path: /

server:
  port: ${API_PORT}
  context-path: /

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        hbm2ddl:
          auto: update
        ddl-auto:
          update
        dialect: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
