logging:
  level:
    root: FATAL

server:
  port: 8011

spring:
  config:
    import: optional:file:.env[.properties]
  application: 
    name: pages
  datasource:
    url: jdbc:postgresql://localhost:5435/pages
    username: isj01
    password: is067
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
