logging:
  level:
    root: FATAL

server:
    port: 8010

spring:
  application:
    name: services
  datasource:
    url: jdbc:postgresql://localhost:5434/services
    username: isj01
    password: is067
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        hbm2ddl:
          auto: update
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
