# Generated by Django 5.1 on 2025-03-03 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('of', models.IntegerField()),
                ('to', models.IntegerField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('file', models.FileField(blank=True, max_length=100000, null=True, upload_to='uploads/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportcategory')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
