# Generated by Django 5.1 on 2025-03-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Line', 'Line'), ('Tension Line', 'Tension Line'), ('Scatter', 'Scatter'), ('Bar', 'Bar'), ('Pie', 'Pie'), ('Doughnut', 'Doughnut'), ('PolarArea', 'PolarArea'), ('Radar', 'Radar')], max_length=12)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.report')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chart')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chart')),
            ],
        ),
    ]
