# Generated by Django 5.1 on 2025-03-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chart_label_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
        migrations.AddField(
            model_name='report',
            name='chart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.chart'),
        ),
    ]
