# Generated by Django 5.1 on 2025-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chart_report_remove_report_file_report_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, max_length=100000, null=True, upload_to='uploads/'),
        ),
    ]
