# Generated by Django 5.1 on 2025-03-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_label_chart_alter_value_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chart'),
        ),
        migrations.AlterField(
            model_name='value',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chart'),
        ),
    ]
